import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,validateSave,overall,strength,autoLineup,type State,type Training} from '../lib/game.ts';

function play(s:State){s=act(s,{type:'start'});while(!s.match!.done)s=act(s,{type:'segment'});return act(s,{type:'finish'});}
function step(s:State,t:Training='balance'){if(s.event)s=act(s,{type:'event',choice:'team'});s=act(s,{type:'train',training:t});if(s.pending)s=play(s);return s;}
test('18 players, three balanced classes, unique starting eleven',()=>{const s=newGame('試験高校',42);assert.equal(s.players.length,18);assert.equal(new Set(s.lineup).size,11);for(const y of [1,2,3])assert.equal(s.players.filter(p=>p.year===y).length,6);assert.deepEqual(validateSave(JSON.parse(JSON.stringify(s))),s);});
test('training grows players; focused training grows faster; original stays immutable',()=>{const s=newGame('',42),id=s.players[0].id;const focused=act(s,{type:'focus',id});const a=act(s,{type:'train',training:'attack'}),b=act(focused,{type:'train',training:'attack'});assert.equal(s.week,0);assert.equal(a.week,1);const gain=a.players[0].stats.shoot-s.players[0].stats.shoot;assert.ok(gain>0);assert.ok(Math.abs((b.players[0].stats.shoot-s.players[0].stats.shoot)/gain-1.5)<.01);});
test('rest restores fatigue and training cannot skip pending fixtures',()=>{let s=newGame('',12);s.players.forEach(p=>p.fatigue=80);s=act(s,{type:'train',training:'rest'});assert.equal(s.players[0].fatigue,47);s.week=3;s=act(s,{type:'train',training:'balance'});assert.ok(s.pending);assert.throws(()=>act(s,{type:'train',training:'balance'}));});
test('match commands, substitution limit and save/resume at halftime',()=>{let s=newGame('',55);s.week=3;s=act(s,{type:'train',training:'rest'});s=act(s,{type:'start'});const original=[...s.lineup];for(let i=0;i<3;i++){const p=s.players.find(p=>!s.match!.used.includes(p.id))!;s=act(s,{type:'swap',index:i+1,id:p.id});}assert.equal(s.match!.subs,3);assert.throws(()=>act(s,{type:'swap',index:5,id:s.players.find(p=>!s.match!.used.includes(p.id))!.id}));for(let i=0;i<3;i++)s=act(s,{type:'segment'});assert.equal(s.match!.minute,45);const loaded=validateSave(JSON.parse(JSON.stringify(s)));assert.deepEqual(act(s,{type:'segment'}),act(loaded,{type:'segment'}));while(!s.match!.done)s=act(s,{type:'segment'});assert.equal(s.records.games,1);assert.throws(()=>act(s,{type:'segment'}));s=act(s,{type:'finish'});assert.deepEqual(s.lineup,original);assert.equal(s.week,4);});
test('graduation preserves 18 players, advances lower classes and records history',()=>{let s=newGame('',91);const graduates=s.players.filter(p=>p.year===3).map(p=>p.id),younger=s.players.filter(p=>p.year===1).map(p=>p.id);s.week=47;s=step(s,'rest');assert.equal(s.season,2);assert.equal(s.week,0);assert.equal(s.history.length,1);assert.equal(s.history[0].graduates.length,6);assert.ok(graduates.every(id=>!s.players.some(p=>p.id===id)));assert.ok(younger.every(id=>s.players.find(p=>p.id===id)?.year===2));assert.equal(s.players.length,18);validateSave(s);});
test('formation fit, fatigue, and facilities affect gameplay',()=>{let s=newGame('',41);const base=strength(s);s.players.forEach(p=>p.fatigue=90);assert.ok(strength(s)<base);s=act(s,{type:'formation',formation:'3-4-3'});assert.equal(s.lineup.length,11);s.funds=100;s=act(s,{type:'upgrade'});assert.equal(s.facilities,2);assert.equal(s.funds,60);assert.throws(()=>act({...s,funds:0},{type:'upgrade'}));});
test('malformed and out of range save files rejected',()=>{for(const bad of [null,{}, {...newGame('',12),week:48},{...newGame('',12),players:[]},{...newGame('',12),lineup:Array(11).fill(1)},{...newGame('',12),formation:'0-0-0'},{...newGame('',12),funds:Infinity},{...newGame('',12),history:[{}]}])assert.throws(()=>validateSave(bad));});
test('10 seasons simulate without broken states and save roundtrips',()=>{let s=newGame('試験高校',789);let actions=0;while(s.season<=10){const f=s.players.reduce((a,p)=>a+p.fatigue,0)/18;s=step(s,f>35?'rest':s.week%3===0?'possession':'balance');if(s.funds>=s.facilities*40&&s.facilities<5)s=act(s,{type:'upgrade'});autoLineup(s);validateSave(JSON.parse(JSON.stringify(s)));assert.ok(s.players.every(p=>overall(p)<=99));actions++;assert.ok(actions<600);}assert.equal(s.history.length,10);assert.ok(s.records.games>=60);});
test('qualifier/national progression and knockout loss never block the calendar',()=>{for(let seed=1;seed<=20;seed++){let s=newGame('',seed);s.week=27;s.alive=true;s=step(s,'rest');if(!s.alive){assert.equal(s.qualified,false);assert.ok(!s.pending);while(s.week<36)s=step(s,'rest');assert.ok(!s.pending);}else assert.equal(s.week,28);}});
test('match log lines stay in chronological order',()=>{for(let seed=1;seed<=25;seed++){let s=newGame('',seed);s.week=3;s=act(s,{type:'train',training:'rest'});s=act(s,{type:'start'});while(!s.match!.done)s=act(s,{type:'segment'});const minutes=s.match!.logs.map(l=>/^(\d+)′/.exec(l)).filter(Boolean).map(m=>+m![1]);for(let i=1;i<minutes.length;i++)assert.ok(minutes[i-1]>=minutes[i],`seed ${seed} out of order: ${minutes.join(',')}`);}});
